### ISSUE TITLE
build-osuosl-aix71-ppc64-1: tests which specify -Xgc:metronome fail (openj9 option)

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1803]
Tests which use the openj9 command line option `-Xgc:metronome` fail when run on `build-osuosl-aix71-ppc64-1` but pass when run on `test-ibm-aix71-ppc64-2`.

The symptoms are the same as those described in https://github.com/eclipse/openj9/issues/10579, where the underlying reason was said to be "AIX machine is not configured for High Resolution Clock to support Metronome".

**Comment by aixtools** [comment]
The issues discussed in the note above have been addressed in the AIX playbook. Apparently the changes were never applied manually to the osuosl systems and/or the playbooks were not re-run to update user settings.

**Comment by karianna** [comment]
@aixtools Safe to close this now in that case?

**Comment by sxa** [comment]
@lumpfish Are you able to verify whether this now works? It's clear from this issue which test showed the problem

**Comment by aixtools** [comment]
Likewise, as I mentioned in #1816 (read asked) the possibility of just rebuilding `build-osuosl-aix71-ppc64-1`, and perhaps later `build-osuosl-aix71-ppc64-2` - rather than trying to dig in a system that has been manually adjusted several times. Especially if `test-osuosl-aix71-ppc64-1` seems to be working correctly - which was recently built using the latest playbook(s).

**Comment by lumpfish** [comment]
The tests still fail when run on build-osuosl-aix71-ppc64-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6081/consoleFull

This will rerun on of the tests affected:  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_jvmtitests_5

**Comment by aixtools** [comment]
I looked at the changes listed in https://github.com/eclipse/openj9/issues/10579#issuecomment-742627758 - and I had already added the capabilities to jenkins.

What I notice is still different - root was not the administrator of the group staff (should not influence capabilities), but the shell is still `ksh` and not `bash`.

Further, while `/home/jenkins/.profile` does not exist - there is nothing (simple) to find to describe what variables are being set by /etc/environment and/or /etc/profile.

for the record:

```
# lsuser -a capabilities fsize  cpu rss stack nofiles jenkins
jenkins capabilities=CAP_NUMA_ATTACH,CAP_BYPASS_RAC_VMM,CAP_PROPAGATE fsize=-1 cpu=-1 rss=65536 stack=65536 nofiles=2000
```

**Comment by aixtools** [comment]
I found something - thx Adam for your assistance!

There is an RBAC privilege associated using the realtime clock (PV_PROC_RTCLK) - and my guess is that AIX 7.1 TL5 and later use the CAP_* capabilities to activate that.

What needs to be verified now is if the changes I made to build-osuosl-aix71-ppc64-1 fix the test issue. If so, I'll open a PR and make an addition to the playbooks - specific for AIX 7.1 TL4 (if TL5 is working using the capabilities attribute).

**Comment by aixtools** [comment]
Verified in several grinder jobs - the metronome setting is fixed with some additional RBAC settings. I'll make an additional role (rbac) for AIX so that this is fixed in AIX 7.1 TL4 systems. 

It seems the CAP_* capabilities provide the kernel privilege in a different way.

a) This could be closed - as fixed aka fix known - or
b) wait for the PR to be merged (but that may take a lot longer).

**Comment by aixtools** [comment]
As far as running the test goes - this can be closed. -Xgcpolicy:metronome works on both build-osuosl-aix71-ppc-{1,2} systems. See https://ci.adoptopenjdk.net/job/Grinder/6233/console (build-2) and https://ci.adoptopenjdk.net/job/Grinder/6202/console (build-1)

**Comment by sxa** [comment]
@lumpfish Was the `ci.role.test` label removed from this machine? While this now seems to be resolved I'm curious as to what it was that flagged up this issue given that the tests aren't currently able to be selected for that machine (May be that it was discussed/mentioned elsewhere but I'm just looking at this issue for now)

**Comment by lumpfish** [comment]
As I recall the role was removed from the machine before the Jan 2021 release runs because there were a number of known issues on that machine which might cause tests to fail.

**Comment by sxa** [comment]
OK I've added the label back onto [build-osuosl-aix71-ppc64-2](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-2/) again to increase capacity - I prefer to keep one dedicated build system but happy to share the second with test for now. That explains why AIX has been a limiting factor in terms of general testing capacity recently.
