### ISSUE TITLE
test-azure-win2012r2-x64-1: testOSMXBeanLocal_0 Error: getTotalSwapSpaceSize() API returned -1

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1805]
The same failure is reported by these external.functional tests with openj9 jdk8 running on test-azure-win2012r2-x64-1:
```
testOSMXBeanLocal_0
testOSMXBeanLocal_1
testOSMXBeanRemote_0
testOSMXBeanRemote_1
```
e.g. https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/63/

The tests pass on  build-alibaba-win2012r2-x64-2- e.g. https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/62.

The symptoms are the same as reported in https://github.com/eclipse/openj9/issues/7716, which suggests there may be an issue with the cygwin configuration, though that issue talks specifically about a win32 jdk and this failure was seen on the openj9 jdk8 win64_xl build:
```
17:55:47  openjdk version "1.8.0_282-internal"
17:55:47  OpenJDK Runtime Environment (build 1.8.0_282-internal-202101051709-b07)
17:55:47  Eclipse OpenJ9 VM (build master-1910cfa3a, JRE 1.8.0 Windows Server 2012 R2 amd64-64-Bit 20210105_550 (JIT enabled, AOT enabled)
17:55:47  OpenJ9   - 1910cfa3a
17:55:47  OMR      - a9b64bdc8
17:55:47  JCL      - 722ab284 based on jdk8u282-b07)
```

Output of failing test:
```
19:46:46  ===============================================
19:46:46  Running test testOSMXBeanLocal_0 ...
19:46:46  ===============================================
19:46:46  testOSMXBeanLocal_0 Start Time: Tue Jan  5 19:46:41 2021 Epoch Time (ms): 1609876001610
19:46:46  "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:destroyAll; "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdkbinary/j2sdk-image\\bin\\java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
19:46:46  JVMSHRC005I No shared class caches available
19:46:46  JVMSHRC005I No shared class caches available
19:46:46  cache cleanup done
19:46:46  variation: Mode100
19:46:46  JVM_OPTIONS:  -Xint -Xgcpolicy:optthruput -Xnocompressedrefs 
19:46:46  { itercnt=1; \
19:46:46  mkdir -p "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TKG\\test_output_16098696244505\\testOSMXBeanLocal_0"; \
19:46:46  cd "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TKG\\test_output_16098696244505\\testOSMXBeanLocal_0"; \
19:46:46  export PATH="/cygdrive/c/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdkbinary/openjdk-test-image/openj9:/cygdrive/c/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdkbinary/j2sdk-image/jre/bin/default:/cygdrive/c/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdkbinary/j2sdk-image/jre/bin/j9vm:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/usr/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Strawberry/perl/bin:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/Java/jdk8u172-b11/bin:/cygdrive/c/apache-ant/apache-ant-1.10.3/bin:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/cygdrive/c/Program Files/Microsoft SQL Server/120/Tools/Binn"; \
19:46:46  "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdkbinary/j2sdk-image\\bin\\java"  -Xint -Xgcpolicy:optthruput -Xnocompressedrefs  \
19:46:46  -DRUNLOCAL=true \
19:46:46  -cp "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests///..//jvmtest\\TestConfig\\resources;C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TKG\\lib\\testng.jar;C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TKG\\lib\\jcommander.jar;C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests///..//jvmtest\\functional\\JLM_Tests\\jlm_tests.jar" \
19:46:46  org.testng.TestNG -d "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TKG\\test_output_16098696244505\\testOSMXBeanLocal_0" "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests///..//jvmtest\\functional\\JLM_Tests\\testng.xml" \
19:46:46  -testnames testOSMXBean \
19:46:46  -groups level.extended \
19:46:46  -excludegroups d.*.win_x86-64,d.*.arch.x86,d.*.os.win,d.*.bits.64,d.*.generic-all; \
19:46:46  if [ $? -eq 0 ] ; then echo ""; echo "testOSMXBeanLocal_0""_PASSED"; echo ""; cd C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/;  else echo ""; echo "testOSMXBeanLocal_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TKG\\test_output_16098696244505\\TestTargetResult";
19:46:46  [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is C:/Users/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_windows_xl/openjdk-tests/\\TestConfig\\resources\\excludes\\latest_exclude_8.txt
19:46:46  ...
19:46:46  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
19:46:46  ...
19:46:46  
19:46:46  [TestOperatingSystemMXBean] [INFO]  ----------------------------------------------------------
19:46:46  [TestOperatingSystemMXBean] [INFO]  Starting the OperatingSystemMXBean usage API tests........
19:46:46  [TestOperatingSystemMXBean] [INFO]  ----------------------------------------------------------
19:46:46  [TestOperatingSystemMXBean] [INFO] Tests starting at: 1609876002323 ms.
19:46:46  [TestOperatingSystemMXBean] [INFO] Testing getTotalPhysicalMemory() & getFreePhysicalMemorySize() APIs
19:46:46  [TestOperatingSystemMXBean] [INFO] Testing getTotalSwapSpaceSize() & getFreeSwapSpaceSize() APIs
19:46:46  [TestOperatingSystemMXBean] [INFO] Tests finished at: 1609876002328 ms.
19:46:46  FAILED: runTestOSMXBean
19:46:46  java.lang.AssertionError: Error: getTotalSwapSpaceSize() API returned -1, test failed
19:46:46  	at org.testng.Assert.fail(Assert.java:96)
19:46:46  	at org.openj9.test.management.TestOperatingSystemMXBean.test_SwapSpaceSizeAPIs(TestOperatingSystemMXBean.java:227)
19:46:46  	at org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean(TestOperatingSystemMXBean.java:171)
19:46:46  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:46:46  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:46:46  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:46:46  	at java.lang.reflect.Method.invoke(Method.java:498)
19:46:46  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
19:46:46  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
19:46:46  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
19:46:46  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
19:46:46  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
19:46:46  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
19:46:46  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
19:46:46  	at org.testng.TestRunner.run(TestRunner.java:505)
19:46:46  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
19:46:46  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
19:46:46  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
19:46:46  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
19:46:46  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
19:46:46  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
19:46:46  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
19:46:46  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
19:46:46  	at org.testng.TestNG.runSuites(TestNG.java:1049)
19:46:46  	at org.testng.TestNG.run(TestNG.java:1017)
19:46:46  	at org.testng.TestNG.privateMain(TestNG.java:1354)
19:46:46  	at org.testng.TestNG.main(TestNG.java:1323)
19:46:46  
19:46:46  
19:46:46  ===============================================
19:46:46      testOSMXBean
19:46:46      Tests run: 1, Failures: 1, Skips: 0
19:46:46  ===============================================
```

**Comment by sxa** [comment]
Have these previously passed on the same machine or is it a new failure on those?

@Willsparker or @Haroon-Khel Can you check to see if there might be something differnet between the cygwin installation on the systems (there is [a suggestion](https://github.com/eclipse/openj9/issues/7716#issuecomment-558719129) that it's a shift from openssh 7.9 to 8.0 - although if that's the case it would be odd for it to work on the newer machine from alibaba) and also a (possibly red herring) that a space space difference may be responsible.

**Comment by Willsparker** [comment]
`test-azure-win2012r2-x64-1` 's `ssh -V` output: 
```
OpenSSH_7.7p1, OpenSSL 1.0.2o  27 Mar 2018
```
`build-alibaba-win2012r2-x64-1`'s `ssh -V` output:
```
OpenSSH_8.3p1, OpenSSL 1.1.1f  31 Mar 2020
```
As far as I'm aware, we haven't changed the version on `test-azure-win2012r2-x64-1` recently though, so not sure why it'd suddenly stop working.

**Comment by lumpfish** [comment]
Please see comment https://github.com/eclipse/openj9/issues/7716#issuecomment-755328706 about what to fix.

**Comment by Willsparker** [comment]
Alright, I do those changes :-)

**Comment by Willsparker** [comment]
Those have been done on `test-azure-win2012r2-x64-1` :-) Can someone confirm this has been fixed?

**Comment by lumpfish** [comment]
I'll retest today.

**Comment by Willsparker** [comment]
How'd the retest go?

**Comment by lumpfish** [comment]
Sorry, got sidetracked.  Will do it now.

**Comment by lumpfish** [comment]
Still failed on test-azure-win2012r2-x64-1, same error: https://ci.adoptopenjdk.net/job/Grinder/5892/consoleFull.
Passed on build-azure-win2012r2-x64-2: https://ci.adoptopenjdk.net/job/Grinder/5891/consoleFull

**Comment by Willsparker** [comment]
That is ... a shame - I double checked, the `openssh` version of both is `8.2p1`. I also double checked both machines, the `jenkins` user is in the `Performance Log Users` group, as required ( `build-azure-win2012r2-x64-1` 's Jenkins user is in all the same groups as `build-azure-win2012r2-x64-2` ).
Is there any way of making sure that that test is returning -1 due to the error that https://github.com/eclipse/openj9/issues/7716#issuecomment-755328706 is suppose to fix?

**Comment by lumpfish** [comment]
What does being in the Performance Log Users group mean?  Could there be a difference in that between the machines?  If the user has been added to the group is a reboot / restart of something required for the change to take effect?
I'm not familiar with the test case myself but the fact that the test only fails on this machine and the error has been seen before (and solved in this way) in the past does suggest to me that somewhere this required permission is not granted.

**Comment by sxa** [comment]
I would imagine that unless the jenkins agent service is restarted it won't be picking up any new changes to the groups it is in, so as @lumpfish says I'd try that

**Comment by Willsparker** [comment]
Hang on - I was being an idiot and got the `test` and `build` machines mixed up ... :facepalm: 
`test-azure-win2012r2-x64-1` 's Jenkins user is now in  `Performance Log Users` (it wasn't before)- I've restarted the jenkins agent as well.

**Comment by Willsparker** [comment]
I've resubmitted the [Grinder](https://ci.adoptopenjdk.net/job/Grinder/5893/).

**Comment by Willsparker** [comment]
Woo-Hoo, it passed! Closing issue :)
